import { jsPDF } from "jspdf";
import { ExtractedQuestion } from "../types";

export function generateStudyGuidePDF(
  subjectName: string,
  questionBankName: string,
  questions: ExtractedQuestion[]
) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Render Cover Page
  drawCoverPage(doc, pageWidth, pageHeight, subjectName, questionBankName, questions.length);

  // Render Content Pages
  doc.addPage();
  let y = margin + 10;

  function ensureSpace(heightNeeded: number) {
    if (y + heightNeeded > pageHeight - margin - 15) {
      doc.addPage();
      y = margin + 15; // Set starting Y after running header room
    }
  }

  questions.forEach((q, index) => {
    if (!q.selected || q.status !== "completed") return;

    // Check size for Question Header
    ensureSpace(35);

    // Draw Category Tag
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(24, 119, 242); // Blue accent
    doc.text(q.category.toUpperCase(), margin, y);
    y += 5;

    // Draw Question Title
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42); // Deep Charcoal Slate
    const splitQuestion = doc.splitTextToSize(`Q${index + 1}. ${q.text}`, contentWidth);
    doc.text(splitQuestion, margin, y);
    y += (splitQuestion.length * 6) + 4;

    // Output 5-Mark Answer
    if (q.mark5 && (q.answerType === "5mark" || q.answerType === "both")) {
      const answerObj = q.mark5;
      const textToRender = answerObj.userEditedText || answerObj.text;
      
      ensureSpace(40);
      
      // Header for 5-Mark
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(71, 85, 105); // Gray-slate
      doc.text(`[5-Mark Template]  •  Word Count: ${answerObj.wordCount} words`, margin, y);
      y += 6;

      // Inner text
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85); // Slate
      const splitAnswer = doc.splitTextToSize(textToRender, contentWidth);
      
      splitAnswer.forEach((line: string) => {
        ensureSpace(6);
        doc.text(line, margin, y);
        y += 5.5;
      });
      y += 6;
    }

    // Output 10-Mark Answer
    if (q.mark10 && (q.answerType === "10mark" || q.answerType === "both")) {
      const answerObj = q.mark10;
      const textToRender = answerObj.userEditedText || answerObj.text;
      
      ensureSpace(50);
      
      // Header for 10-Mark
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(71, 85, 105);
      doc.text(`[10-Mark Detailed Answer]  •  Word Count: ${answerObj.wordCount} words`, margin, y);
      y += 6;

      // Inner text
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85);
      const splitAnswer = doc.splitTextToSize(textToRender, contentWidth);

      splitAnswer.forEach((line: string) => {
        ensureSpace(6);
        doc.text(line, margin, y);
        y += 5.5;
      });
      y += 6;
    }

    // Draw separating line between questions if not the last item
    if (index < questions.length - 1) {
      ensureSpace(15);
      doc.setDrawColor(226, 232, 240); // Light gray slate
      doc.setLineWidth(0.4);
      doc.line(margin, y, pageWidth - margin, y);
      y += 12;
    }
  });

  // Post-Process: Headers and Footers for all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    
    // Page 1 is Cover (pristine)
    if (i > 1) {
      // Header line
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // Cool Slate Gray
      doc.text("TheLastMinute-Agent  |  Exam Syllabus Answer Dossier", margin, margin - 5);
      doc.text(`Course Module: ${subjectName.substring(0, 30)}${subjectName.length > 30 ? "..." : ""}`, pageWidth - margin - 50, margin - 5, { align: "right" });
      
      doc.setDrawColor(203, 213, 225);
      doc.setLineWidth(0.3);
      doc.line(margin, margin - 3, pageWidth - margin, margin - 3);

      // Footer line
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, pageHeight - margin + 2, pageWidth - margin, pageHeight - margin + 2);
      
      doc.text("Generated by TheLastMinute-Agent  •  Study Hard, Score High!", margin, pageHeight - margin + 7);
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - margin + 7, { align: "right" });
    }
  }

  // Save the document
  const fileName = `StudyGuide_${subjectName.replace(/\s+/g, "_").substring(0, 20)}.pdf`;
  doc.save(fileName);
}

function drawCoverPage(
  doc: jsPDF,
  pageWidth: number,
  pageHeight: number,
  subjectName: string,
  questionBankName: string,
  questionCount: number
) {
  // Top Banner Accent
  doc.setFillColor(15, 23, 42); // Primary Dark Charcoal
  doc.rect(0, 0, pageWidth, 45, "F");

  // Subtle accent line
  doc.setFillColor(99, 102, 241); // Indigo Accent
  doc.rect(0, 45, pageWidth, 3, "F");

  // Banner Text
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(224, 231, 255); // Indigo Tint
  doc.text("EXAM ACCELERATION DOSSIER", 20, 20);

  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text("THE LAST MINUTE STUDY COMPASS", 20, 32);

  // Main Card Area background
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(20, 65, pageWidth - 40, 95, 3, 3, "FD");

  // Title info inside Card
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  doc.text("CURRICULUM SPECIFICATIONS SOURCED:", 28, 77);

  // Subject Name
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  const splitSubject = doc.splitTextToSize(subjectName, pageWidth - 60);
  doc.text(splitSubject, 28, 86);
  
  let currentY = 86 + (splitSubject.length * 7);

  // Question Bank Source
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text("QUESTION BANK RESOURCE:", 28, currentY);
  
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(51, 65, 85);
  const splitQB = doc.splitTextToSize(questionBankName, pageWidth - 60);
  doc.text(splitQB, 28, currentY + 6);

  currentY += 6 + (splitQB.length * 6) + 4;

  // Metadata Grid
  doc.setDrawColor(203, 213, 225);
  doc.line(28, currentY, pageWidth - 28, currentY);
  currentY += 8;

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("COMPILED DATE", 28, currentY);
  doc.text("COVERAGE TARGETS", 95, currentY);
  doc.text("TOTAL QUESTIONS", 155, currentY);

  const localTime = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(localTime, 28, currentY + 6);
  doc.text("5-Mark & 10-Mark Schemes", 95, currentY + 6);
  doc.text(`${questionCount} Solved Items`, 155, currentY + 6);

  // Study Guidelines section (bottom)
  let instructionsY = 180;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("STUDY DISCIPLINE GUIDE", 20, instructionsY);
  
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(1);
  doc.line(20, instructionsY + 2, 45, instructionsY + 2);

  const guideLines = [
    "• Sourced Answers: Key concepts have been precision-matched directly against syllabus material.",
    "• 5-Mark Answers (80-100 Words): Focus heavily on core definitions, brief outlines, and keyword lists.",
    "• 10-Mark Answers (180-200 Words): Designed for structural completeness with introductions and applications.",
    "• Retain Keywords: Memorize the bold highlighted headers to write high-scoring answers in exam contexts.",
  ];

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  let gy = instructionsY + 10;
  guideLines.forEach((line) => {
    const splitLine = doc.splitTextToSize(line, pageWidth - 40);
    doc.text(splitLine, 20, gy);
    gy += (splitLine.length * 5) + 2;
  });

  // Footer Copyright
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by TheLastMinute-Agent application system.", pageWidth / 2, pageHeight - 15, { align: "center" });
}
